// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Dynamic CRM tool helper")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.20.5")>]
[<assembly: AssemblyInformationalVersionAttribute("5.20.5")>]
[<assembly: AssemblyFileVersionAttribute("5.20.5")>]
[<assembly: AssemblyMetadataAttribute("BuildDate","2021-04-22")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make Dynamic CRM tool helper"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "5.20.5"
    let [<Literal>] AssemblyInformationalVersion = "5.20.5"
    let [<Literal>] AssemblyFileVersion = "5.20.5"
    let [<Literal>] AssemblyMetadata_BuildDate = "2021-04-22"
